import { $ } from "~/generated/zeus";
import { generateQuery } from "~/graphql/graphqlGen";

// Which mined cluster each lineup sits in, and nothing else. The meta's own
// count of the lineups in a cluster includes private and archived ones the
// viewer cannot open, so "written up" is answered from what they can see: the
// cluster key is a column every lineup carries, generated by the same
// expression the clusters are keyed by.
export const utilityLineupBucketsQuery = generateQuery({
  utility_lineups: [
    {
      where: $("where", "utility_lineups_bool_exp!"),
      limit: $("limit", "Int!"),
    },
    {
      id: true,
      lineup_bucket: true,
    },
  ],
});

// Where every lineup the viewer can open lands, across all maps, and nothing
// else: the maps index draws each map's library as marks on its radar. Five
// scalars a row, capped by the caller.
export const utilityLibraryLandingsQuery = generateQuery({
  utility_lineups: [
    {
      where: $("where", "utility_lineups_bool_exp!"),
      order_by: $("order_by", "[utility_lineups_order_by!]"),
      limit: $("limit", "Int!"),
    },
    {
      id: true,
      map_name: true,
      utility_type: true,
      land_x: true,
      land_y: true,
      land_z: true,
    },
  ],
});
